AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation for WebSocket Lambda Functions and WebSocket API Gateway

Resources:

  ### WebSocket API Gateway ###
  WebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: QuizzyWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action


  ### Lambda Functions ###
  ConnectLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: WebSocketConnectFunction
      Runtime: python3.11
      Handler: connectSocket.lambda_handler
      Code:
        S3Bucket: lambda-code-files-news
        S3Key: code/connectSocket.zip
      Role: arn:aws:iam::590183793287:role/LabRole
      Environment:
        Variables:
          WEBSOCKET_API_URL: !Sub "https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/production"

  DisconnectLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: WebSocketDisconnectFunction
      Runtime: python3.11
      Handler: disconnectSocket.lambda_handler
      Code:
        S3Bucket: lambda-code-files-news
        S3Key: code/disconnectSocket.zip
      Role: arn:aws:iam::590183793287:role/LabRole
      Environment:
        Variables:
          WEBSOCKET_API_URL: !Sub "https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/production"

  ScoreUpdateLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ScoreUpdateFunction
      Runtime: python3.11
      Handler: scoreUpdate.lambda_handler
      Code:
        S3Bucket: lambda-code-files-news
        S3Key: code/scoreUpdate.zip
      Role: arn:aws:iam::590183793287:role/LabRole
      Environment:
        Variables:
          WEBSOCKET_API_URL: !Sub "https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/production"

  StartQuizLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: StartQuizFunction
      Runtime: python3.11
      Handler: startQuiz.lambda_handler
      Code:
        S3Bucket: lambda-code-files-news
        S3Key: code/startQuiz.zip
      Role: arn:aws:iam::590183793287:role/LabRole
      Environment:
        Variables:
          WEBSOCKET_API_URL: !Sub "https://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/production"

  ### WebSocket API Gateway Routes ###
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $connect
      Target: !Sub "integrations/${ConnectIntegration}"

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: $disconnect
      Target: !Sub "integrations/${DisconnectIntegration}"

  ScoreUpdateRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: scoreUpdate
      Target: !Sub "integrations/${ScoreUpdateIntegration}"

  StartQuizRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketApi
      RouteKey: startQuiz
      Target: !Sub "integrations/${StartQuizIntegration}"

  ### Lambda Integrations ###
  ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConnectLambda.Arn}/invocations"

  DisconnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DisconnectLambda.Arn}/invocations"

  ScoreUpdateIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ScoreUpdateLambda.Arn}/invocations"

  StartQuizIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StartQuizLambda.Arn}/invocations"

  ### API Deployment ###
  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref WebSocketApi
    DependsOn:
      - ConnectRoute
      - DisconnectRoute
      - ScoreUpdateRoute
      - StartQuizRoute

  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketApi
      StageName: production
      DeploymentId: !Ref WebSocketDeployment

Outputs:
  WebSocketApiUrl:
    Value: !Sub "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/production"
    Description: WebSocket API Gateway URL
